<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Does the age difference of actors in movies relationships decrease as the release date becomes more modern?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">THAN</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html">Proposal</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presentation.pdf">Presentation</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./report.html" aria-current="page">Report</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">About</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-and-data" id="toc-introduction-and-data" class="nav-link active" data-scroll-target="#introduction-and-data">Introduction and Data:</a>
  <ul class="collapse">
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question">Research Question:</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">Exploratory Data Analysis</a></li>
  </ul></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">Methodology</a>
  <ul class="collapse">
  <li><a href="#prediction-1" id="toc-prediction-1" class="nav-link" data-scroll-target="#prediction-1">Prediction 1:</a></li>
  <li><a href="#prediction-2" id="toc-prediction-2" class="nav-link" data-scroll-target="#prediction-2">Prediction 2:</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#bootstrapping-and-clt-of-mean-age-gaps" id="toc-bootstrapping-and-clt-of-mean-age-gaps" class="nav-link" data-scroll-target="#bootstrapping-and-clt-of-mean-age-gaps">Bootstrapping and CLT of Mean Age Gaps</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Does the age difference of actors in movies relationships decrease as the release date becomes more modern?</h1>
<p class="subtitle lead">THAN: Report</p>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="introduction-and-data" class="level2">
<h2 class="anchored" data-anchor-id="introduction-and-data">Introduction and Data:</h2>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<p>Our data comes from the Tidy Tuesday repositories on GitHub via the site “Data is Plural.”</p>
<p>The data set, <em>Hollywood Age Gap</em>, was compiled by Lynn Fisher and explores the age difference between actors playing couples in Hollywood movies which demonstrates the male-female power dynamic in the movie industry.</p>
<p><em>Hollywood Age Gap</em> can be accessed <a href="https://github.com/rfordatascience/tidytuesday/blob/75acea5a3a7732436670f9f0d82932e422fe4037/data/2023/2023-02-14/age_gaps.csv">here.</a></p>
<p><em>Hollywood Age Gap</em> has information from upwards of 630 movies, sampled from films from 1935 to 2022, the dataset was most recently updated on February 14th, 2023.</p>
<p><em>Hollywood Age Gap</em>, while mostly compiled by Fisher, is open source and in turn anyone can submit data to the dataset for consideration contingent on three rules:</p>
<ol type="1">
<li>The actors are atleast 17 years old</li>
<li>The actors are actually love interests in the film</li>
<li>The characters can not be animated</li>
</ol>
<p>Observations of the data set include:</p>
<ul>
<li><p>movie_name: the name of the movie</p></li>
<li><p>release_year: the year the movie was released</p></li>
<li><p>director: the movie’s director</p></li>
<li><p>actor_1_name/actor_2_name: the names of the actors whose characters are in a relationship</p></li>
<li><p>actor_1_birthdate/actor_2_birthdate: the birthdates of the actors</p></li>
<li><p>actor_1_age/actor_2_age: the ages of the actors when the movie was released</p></li>
<li><p>age_difference: the difference between the ages of the two actors</p></li>
</ul>
<p>Additional variables that were added include:</p>
<ul>
<li><p>age_gap_cat: whether the age difference was greater than 15 years, or 15 years or less.</p>
<ul>
<li>15 Years was chosen given that after 15 years the age gaps is large enough for the older partner to be the parent of the younger partner.</li>
</ul></li>
<li><p>older_partner_gender: the gender of the older partner in the relationship</p></li>
<li><p>decades: what decade the film was released in</p></li>
<li><p>era: whether the film was released pre-1950, between 1950 and 1975, between 1975 and 2000, or post-2000.</p></li>
</ul>
<section id="research-question" class="level3">
<h3 class="anchored" data-anchor-id="research-question">Research Question:</h3>
<p><strong>Does the age difference between actors in movie relationships decrease as the movie’s release date becomes more modern?</strong></p>
<p>Our research will attempt to determine whether the uncomfortable age gaps between male and female romantic interests in movies has been waning over time. This will tell us if criticism within the industry and from viewers has actually been effective in making a change on this issue.</p>
<p>In addition we will explore whether in cases where an age gap is present if the male or female member of the couple tends to be older.</p>
<p>Some other things to explore could be the trends of specific actors/actresses that may have experienced both sides of the age gaps, as well as how this trend exists in movies with multiple couples.</p>
</section>
<section id="exploratory-data-analysis" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/agegap-hetero-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  older_partner_gender count
  &lt;chr&gt;                &lt;int&gt;
1 Female                 215
2 Male                   917</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  older_partner_gender mean_gap
  &lt;chr&gt;                   &lt;dbl&gt;
1 Female                   4.73
2 Male                    11.7 </code></pre>
</div>
</div>
<p>The scatter plot above visualizes the age difference between actors in movie relationships over time. The observations are colored based on the gender of the older partner. The purple best fit line shows the trend of age gaps regardless of gender.</p>
<p>From the plot and summary statistics, we observe that in cases where an age gap is present, the older partner tends to be male (215 observations where the older partner was female, 917 where the older partner was male.) And in cases where the older partner is female, the age difference tends to be smaller than the age difference for couples where the older partner is male (mean of 4.73 years compared to 11.7 years respectively.)</p>
<p>Additionally, the majority of the observations appear in the last 40 years and there are not many observations from the 1930s and 1940s because the creation of Hollywood movies was just beginning.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/gap-size-decades-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The bar chart above groups movie observations into the decade that they were released. The plot shows that the proportion of films containing age gaps of over 15 years decreases over time.</p>
<p>In the 1940s, over 80% of films had a large age gap of over 15 years. This proportion could be attributed to World War II, which resulted in younger men enlisting in the military rather than staring in Hollywood films.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/agegap-directors-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The box plot above visualizes the mean age difference in films by the five directors most represented in <em>Hollywood Age Gaps</em>. The plot shows that some directors, like Woody Allen and John Glen, when compared to the mean age difference of heterosexual couples in the dataset (<span class="math inline">\(\mu = 10.4\)</span>) tend to produce movies with a larger than average age gap; whereas Mike Newell’s movies contain below average sized age gaps.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/agegap-samesex-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Unlike the data on heterosexual couples, overtime the age gaps shown in films depicting same sex couples has increased.</p>
</section>
</section>
<section id="methodology" class="level2">
<h2 class="anchored" data-anchor-id="methodology">Methodology</h2>
<p>Since same-sex couples have only begun to be shown in film in the last couple decades, we will filter the data set so that it only contains information about movies with heterosexual couples.</p>
<section id="prediction-1" class="level3">
<h3 class="anchored" data-anchor-id="prediction-1">Prediction 1:</h3>
<p><strong>We predict that overtime the mean age gap between couples has decreased and that the proportion of movies with large age gaps today is less that it was in the past.</strong></p>
<p>We believe this change could be attributed to criticism within the film industry</p>
<ol type="1">
<li><p>We will look at individual 25 year eras of film production, calculating the true mean age gap found in films produced during the years pre-1950, 1950-1975, 1975-2000, and post-2000. By comparing the confidence intervals produced either by bootstrapping or CLT (based on whether data fits CLT requirements), we can find a better understanding of how age gaps changed between each era.</p></li>
<li><p>We will also fit a linear regression model to the data, to see how well the year a film was released can predict the age gap found in the film. We will look at the r-squared of this model to show its strength and analyze the results significance in regards to our hypothesis that as the year becomes more modern age gaps decrease.</p></li>
<li><p>We will also fit a logistic regression model considering other factors that could help create a more accurate model, including the gender of the older partner, and the director of the film. To test the theory that director could play a role in the age gaps portrayed, we will fit a regression model to the observations from the five most common directors in the data set.</p></li>
<li><p>Further, we will preform a hypothesis test to determine whether our hypothesis that age gaps are smaller today than they were in the past is accurate, finding a p-value to assess our null hypothesis that the mean age gaps today are the same as those in the past.</p></li>
</ol>
</section>
<section id="prediction-2" class="level3">
<h3 class="anchored" data-anchor-id="prediction-2">Prediction 2:</h3>
<p><strong>We predict that the age difference is greater in couples where the older partner is male.</strong></p>
<p>To investigate whether the age gap for couples where the older partner is male is greater than the age gap for couples where the older partner is female we will perform a hypothesis test on the difference in mean age differences.</p>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="bootstrapping-and-clt-of-mean-age-gaps" class="level3">
<h3 class="anchored" data-anchor-id="bootstrapping-and-clt-of-mean-age-gaps">Bootstrapping and CLT of Mean Age Gaps</h3>
<p>From the EDA scatterplot of age gaps in heterosexual couples, we observe that all three best fit lines are trending negatively, indicating a decrease in the age gaps over time. This observation will be explored further in the next section through the use of bootstrapping and CLT (based on sample size) to find the true mean of different eras in time.</p>
<p>In order to use the Central Limit Theorem, the sample size must be greater than 30 and the data must show independence. <em>Hollywood Agegap</em> was randomly sampled, meeting the independence requirement.</p>
<ul>
<li><p>Pre-1950: <span class="math inline">\(n = 19 &lt; 30\)</span></p></li>
<li><p>1950-1975: <span class="math inline">\(n = 87 &gt; 30\)</span></p></li>
<li><p>1975-2000: <span class="math inline">\(n = 283 &gt; 30\)</span></p></li>
<li><p>Post-2000: <span class="math inline">\(n = 766 &gt; 30\)</span></p></li>
</ul>
<p>Based on sample size, we can use CLT for all eras besides pre-1950 films where will use bootstrapping.</p>
<section id="pre-1950" class="level4">
<h4 class="anchored" data-anchor-id="pre-1950">pre-1950</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  lower upper
  &lt;dbl&gt; &lt;dbl&gt;
1  12.9  21.1</code></pre>
</div>
</div>
<p>We can say with 95% confidence that the true mean age gap in pre-1950 films was between 12.9 and 21.1 years.</p>
</section>
<section id="section" class="level4">
<h4 class="anchored" data-anchor-id="section">1950-1975</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.32864 16.38400</code></pre>
</div>
</div>
<p>We can say with 95% confidence that the true mean age gap in films released between 1950 and 1975 was between 12.3 and 16.4 years.</p>
</section>
<section id="section-1" class="level4">
<h4 class="anchored" data-anchor-id="section-1">1975-2000</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.30298 15.40967</code></pre>
</div>
</div>
<p>We can say with 95% confidence that the true mean age gap in films released between 1975 and 2000 was between 13.3 and 15.4 years.</p>
</section>
<section id="post-2000" class="level4">
<h4 class="anchored" data-anchor-id="post-2000">post-2000</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1]  8.901113 10.020558</code></pre>
</div>
</div>
<p>We can say with 95% confidence that the true mean age gap in films released after 2000 was between 8.9 and 10.0 years.</p>
</section>
<section id="analysis-of-confidence-intervals" class="level4">
<h4 class="anchored" data-anchor-id="analysis-of-confidence-intervals">Analysis of Confidence Intervals</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can observe that over time, the upper bound of the interval has consistently decreased, and the lower bound (besides in the 1975-2000 era) has also decreased, indicating a decrease in the true mean of age gaps over time. This is consistent with what we observed in the scatterplot of age gaps in heterosexual movie couples.</p>
</section>
<section id="linear-regression-model-year-to-age-difference" class="level4">
<h4 class="anchored" data-anchor-id="linear-regression-model-year-to-age-difference">Linear Regression Model: Year to Age Difference</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04524371</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>parsnip model object


Call:
stats::lm(formula = age_difference ~ release_year, data = data)

Coefficients:
 (Intercept)  release_year  
    231.0808       -0.1103  </code></pre>
</div>
</div>
<p><span class="math inline">\(\widehat{Age Difference} = 231.0808 - 0.1103 * release\_year\)</span></p>
<p>Our linear regression model with release year explains roughly 4.5% variation of the variation in age gaps. This shows that there is not a direct correlation between age gap and the year a film was released but does indicate a negative correlation between age difference and year, supporting our hypothesis that the age difference between actors in movie relationships decreases as the release date becomes more modern.</p>
</section>
<section id="logistic-regression-model-probability-of-a-large-age-gap" class="level4">
<h4 class="anchored" data-anchor-id="logistic-regression-model-probability-of-a-large-age-gap">Logistic Regression Model: Probability of a Large Age Gap</h4>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><span class="math inline">\(\widehat{Age Difference} = 231.0808 - 0.1103 * release\_year\)</span></p>
<p>Our linear regression model with release year explains roughly 4.5% variation of the variation in age gaps. This shows that there is not a direct correlation between age gap and the year a film was released but does indicate a negative correlation between age difference and year, supporting our hypothesis that the age difference between actors in movie relationships decreases as the release date becomes more modern.</p>
</section>
<section id="hypothesis-testing-for-difference-in-means" class="level4">
<h4 class="anchored" data-anchor-id="hypothesis-testing-for-difference-in-means">Hypothesis Testing for Difference in Means</h4>
<p>From the plot we observe that in cases where the older partner is female, the age difference tends to be less than the age difference for couples where the older partner is male. This is investigated in the following code chunk through hypothesis testing.</p>
<p>Null Hypothesis: the true mean age gap for couples where the older partner is male is the same as the true mean age gap for couples where the older partner is female.</p>
<p><span class="math inline">\(H_o: \mu_m - \mu_f = 0\)</span></p>
<p>Alternative Hypothesis: the true mean age gap for couples where the older partner is male is greater than the true mean age gap for couples where the older partner is female.</p>
<p><span class="math inline">\(H_o: \mu_m - \mu_f &gt; 0\)</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  older_partner_gender mean_age
  &lt;chr&gt;                   &lt;dbl&gt;
1 Female                   4.73
2 Male                    11.7 </code></pre>
</div>
</div>
<p><span class="math inline">\(\bar{x}_m - \bar{x}_f = 11.7 - 4.73 = 6.97\)</span></p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Please be cautious in reporting a p-value of 0. This result is an
approximation based on the number of `reps` chosen in the `generate()` step. See
`?get_p_value()` for more information.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  p_value
    &lt;dbl&gt;
1       0</code></pre>
</div>
</div>
<p>With a <span class="math inline">\(p-value &lt; 0.001 &gt; \alpha = 0.05\)</span> we <em>decide</em> to reject the null hypothesis that the true mean age gap for couples where the older partner is male is the same as the true mean age gap for couples where the older partner is female and <em>conclude</em> that there is strong evidence to conclude the alternative hypothesis that the true mean age gap for couples where the older partner is male is greater than the true mean age gap for couples where the older partner is female.</p>
</section>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<ul>
<li>As the release dates of Hollywood films become more modern, the age difference between actors whose characters are in relationships has decreased.</li>
<li>As films become more modern, the proportion of films with age gaps of over 15 years has also consistently decreased.</li>
<li>It is significantly more common for the older partner in couples with an age gap to be male.</li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>